// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	gen "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	AuthAPIService := gen.NewAuthAPIService()
	AuthAPIController := gen.NewAuthAPIController(AuthAPIService)

	OrdersAPIService := gen.NewOrdersAPIService()
	OrdersAPIController := gen.NewOrdersAPIController(OrdersAPIService)

	ProductsAPIService := gen.NewProductsAPIService()
	ProductsAPIController := gen.NewProductsAPIController(ProductsAPIService)

	PromoCodesAPIService := gen.NewPromoCodesAPIService()
	PromoCodesAPIController := gen.NewPromoCodesAPIController(PromoCodesAPIService)

	router := gen.NewRouter(AuthAPIController, OrdersAPIController, ProductsAPIController, PromoCodesAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
