services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      # Путь к файлу спецификации внутри контейнера
      SWAGGER_JSON: /spec/openapi.yaml
    volumes:
      # Монтируем нашу спецификацию в контейнер
      - ./openapi.yaml:/spec/openapi.yaml:ro