// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen

import (
	"encoding/json"
	"net/http"
	"strings"
)

// AuthAPIController binds http requests to an api service and writes the service results to the http response
type AuthAPIController struct {
	service AuthAPIServicer
	errorHandler ErrorHandler
}

// AuthAPIOption for how the controller is set up.
type AuthAPIOption func(*AuthAPIController)

// WithAuthAPIErrorHandler inject ErrorHandler into controller
func WithAuthAPIErrorHandler(h ErrorHandler) AuthAPIOption {
	return func(c *AuthAPIController) {
		c.errorHandler = h
	}
}

// NewAuthAPIController creates a default api controller
func NewAuthAPIController(s AuthAPIServicer, opts ...AuthAPIOption) *AuthAPIController {
	controller := &AuthAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthAPIController
func (c *AuthAPIController) Routes() Routes {
	return Routes{
		"RegisterUser": Route{
			"RegisterUser",
			strings.ToUpper("Post"),
			"/api/v1/auth/register",
			c.RegisterUser,
		},
		"LoginUser": Route{
			"LoginUser",
			strings.ToUpper("Post"),
			"/api/v1/auth/login",
			c.LoginUser,
		},
		"RefreshToken": Route{
			"RefreshToken",
			strings.ToUpper("Post"),
			"/api/v1/auth/refresh",
			c.RefreshToken,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AuthAPIController
func (c *AuthAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"RegisterUser",
			strings.ToUpper("Post"),
			"/api/v1/auth/register",
			c.RegisterUser,
		},
		Route{
			"LoginUser",
			strings.ToUpper("Post"),
			"/api/v1/auth/login",
			c.LoginUser,
		},
		Route{
			"RefreshToken",
			strings.ToUpper("Post"),
			"/api/v1/auth/refresh",
			c.RefreshToken,
		},
	}
}



// RegisterUser - Регистрация пользователя
func (c *AuthAPIController) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var userRegisterRequestParam UserRegisterRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userRegisterRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserRegisterRequestRequired(userRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUserRegisterRequestConstraints(userRegisterRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RegisterUser(r.Context(), userRegisterRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// LoginUser - Аутентификация пользователя
func (c *AuthAPIController) LoginUser(w http.ResponseWriter, r *http.Request) {
	var userLoginRequestParam UserLoginRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&userLoginRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertUserLoginRequestRequired(userLoginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertUserLoginRequestConstraints(userLoginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.LoginUser(r.Context(), userLoginRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RefreshToken - Обновить access token
func (c *AuthAPIController) RefreshToken(w http.ResponseWriter, r *http.Request) {
	var refreshTokenRequestParam RefreshTokenRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&refreshTokenRequestParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRefreshTokenRequestRequired(refreshTokenRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRefreshTokenRequestConstraints(refreshTokenRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RefreshToken(r.Context(), refreshTokenRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
