// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen

import (
	"context"
	"net/http"
	"errors"
)

// PromoCodesAPIService is a service that implements the logic for the PromoCodesAPIServicer
// This service should implement the business logic for every endpoint for the PromoCodesAPI API.
// Include any external packages or services that will be required by this service.
type PromoCodesAPIService struct {
}

// NewPromoCodesAPIService creates a default api service
func NewPromoCodesAPIService() *PromoCodesAPIService {
	return &PromoCodesAPIService{}
}

// CreatePromoCode - Создать промокод
func (s *PromoCodesAPIService) CreatePromoCode(ctx context.Context, promoCodeCreateRequest PromoCodeCreateRequest) (ImplResponse, error) {
	// TODO - update CreatePromoCode with the required logic for this service method.
	// Add api_promo_codes_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, PromoCodeResponse{}) or use other options such as http.Ok ...
	// return Response(201, PromoCodeResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(400, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreatePromoCode method not implemented")
}
