// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen

import (
	"context"
	"net/http"
	"errors"
)

// OrdersAPIService is a service that implements the logic for the OrdersAPIServicer
// This service should implement the business logic for every endpoint for the OrdersAPI API.
// Include any external packages or services that will be required by this service.
type OrdersAPIService struct {
}

// NewOrdersAPIService creates a default api service
func NewOrdersAPIService() *OrdersAPIService {
	return &OrdersAPIService{}
}

// CreateOrder - Создать новый заказ
func (s *OrdersAPIService) CreateOrder(ctx context.Context, orderCreateRequest OrderCreateRequest) (ImplResponse, error) {
	// TODO - update CreateOrder with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, OrderResponse{}) or use other options such as http.Ok ...
	// return Response(201, OrderResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(400, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(409, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(422, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(422, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(429, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrder method not implemented")
}

// GetOrderById - Получить заказ по ID
func (s *OrdersAPIService) GetOrderById(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetOrderById with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderResponse{}) or use other options such as http.Ok ...
	// return Response(200, OrderResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetOrderById method not implemented")
}

// UpdateOrder - Обновить заказ
func (s *OrdersAPIService) UpdateOrder(ctx context.Context, id string, orderUpdateRequest OrderUpdateRequest) (ImplResponse, error) {
	// TODO - update UpdateOrder with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderResponse{}) or use other options such as http.Ok ...
	// return Response(200, OrderResponse{}), nil

	// TODO: Uncomment the next line to return response Response(400, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(400, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(409, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(429, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(429, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateOrder method not implemented")
}

// CancelOrder - Отменить заказ
func (s *OrdersAPIService) CancelOrder(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update CancelOrder with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(401, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(403, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(403, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(404, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(404, ErrorResponse{}), nil

	// TODO: Uncomment the next line to return response Response(409, ErrorResponse{}) or use other options such as http.Ok ...
	// return Response(409, ErrorResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CancelOrder method not implemented")
}
