// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen


import (
	"time"
)



type PromoCodeResponse struct {

	// Уникальный идентификатор
	Id string `json:"id"`

	// Уникальный код промоакции
	Code string `json:"code"`

	DiscountType DiscountType `json:"discount_type"`

	// Значение скидки
	DiscountValue float64 `json:"discount_value"`

	// Минимальная сумма заказа
	MinOrderAmount float64 `json:"min_order_amount"`

	// Максимальное количество использований
	MaxUses int32 `json:"max_uses"`

	// Текущее количество использований
	CurrentUses int32 `json:"current_uses"`

	// Начало срока действия
	ValidFrom time.Time `json:"valid_from"`

	// Окончание срока действия
	ValidUntil time.Time `json:"valid_until"`

	// Активен ли промокод
	Active bool `json:"active"`

	// Время создания
	CreatedAt time.Time `json:"created_at"`
}

// AssertPromoCodeResponseRequired checks if the required fields are not zero-ed
func AssertPromoCodeResponseRequired(obj PromoCodeResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"code": obj.Code,
		"discount_type": obj.DiscountType,
		"discount_value": obj.DiscountValue,
		"min_order_amount": obj.MinOrderAmount,
		"max_uses": obj.MaxUses,
		"current_uses": obj.CurrentUses,
		"valid_from": obj.ValidFrom,
		"valid_until": obj.ValidUntil,
		"active": obj.Active,
		"created_at": obj.CreatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPromoCodeResponseConstraints checks if the values respects the defined constraints
func AssertPromoCodeResponseConstraints(obj PromoCodeResponse) error {
	return nil
}
