// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen




type AuthResponse struct {

	// JWT access token (15-30 минут)
	AccessToken string `json:"access_token"`

	// JWT refresh token (7-30 дней)
	RefreshToken string `json:"refresh_token"`

	User UserResponse `json:"user"`
}

// AssertAuthResponseRequired checks if the required fields are not zero-ed
func AssertAuthResponseRequired(obj AuthResponse) error {
	elements := map[string]interface{}{
		"access_token": obj.AccessToken,
		"refresh_token": obj.RefreshToken,
		"user": obj.User,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUserResponseRequired(obj.User); err != nil {
		return err
	}
	return nil
}

// AssertAuthResponseConstraints checks if the values respects the defined constraints
func AssertAuthResponseConstraints(obj AuthResponse) error {
	if err := AssertUserResponseConstraints(obj.User); err != nil {
		return err
	}
	return nil
}
