// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen


import (
	"time"
)



type UserResponse struct {

	// Уникальный идентификатор пользователя
	Id string `json:"id"`

	// Email пользователя
	Email string `json:"email"`

	Role UserRole `json:"role"`

	// Время создания аккаунта
	CreatedAt time.Time `json:"created_at"`
}

// AssertUserResponseRequired checks if the required fields are not zero-ed
func AssertUserResponseRequired(obj UserResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"email": obj.Email,
		"role": obj.Role,
		"created_at": obj.CreatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserResponseConstraints checks if the values respects the defined constraints
func AssertUserResponseConstraints(obj UserResponse) error {
	return nil
}
