// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen




type OrderCreateRequest struct {

	// Список позиций заказа
	Items []OrderItemCreate `json:"items"`

	// Промокод (опционально)
	PromoCode string `json:"promo_code,omitempty" validate:"regexp=^[A-Z0-9_]{4,20}$"`
}

// AssertOrderCreateRequestRequired checks if the required fields are not zero-ed
func AssertOrderCreateRequestRequired(obj OrderCreateRequest) error {
	elements := map[string]interface{}{
		"items": obj.Items,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertOrderItemCreateRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertOrderCreateRequestConstraints checks if the values respects the defined constraints
func AssertOrderCreateRequestConstraints(obj OrderCreateRequest) error {
	for _, el := range obj.Items {
		if err := AssertOrderItemCreateConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
