// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen


import (
	"errors"
)



type ProductCreateRequest struct {

	// Название товара
	Name string `json:"name"`

	// Описание товара (опционально)
	Description string `json:"description,omitempty"`

	// Цена товара в рублях (> 0)
	Price float64 `json:"price"`

	// Остаток на складе (>= 0)
	Stock int32 `json:"stock"`

	// Категория товара
	Category string `json:"category"`

	Status ProductStatus `json:"status"`
}

// AssertProductCreateRequestRequired checks if the required fields are not zero-ed
func AssertProductCreateRequestRequired(obj ProductCreateRequest) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"price": obj.Price,
		"stock": obj.Stock,
		"category": obj.Category,
		"status": obj.Status,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProductCreateRequestConstraints checks if the values respects the defined constraints
func AssertProductCreateRequestConstraints(obj ProductCreateRequest) error {
	if obj.Price < 0.01 {
		return &ParsingError{Param: "Price", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Stock < 0 {
		return &ParsingError{Param: "Stock", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
