// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen


import (
	"fmt"
)


// DiscountType : Тип скидки промокода
type DiscountType string

// List of DiscountType
const (
	DISCOUNTTYPE_PERCENTAGE DiscountType = "PERCENTAGE"
	DISCOUNTTYPE_FIXED_AMOUNT DiscountType = "FIXED_AMOUNT"
)

// AllowedDiscountTypeEnumValues is all the allowed values of DiscountType enum
var AllowedDiscountTypeEnumValues = []DiscountType{
	"PERCENTAGE",
	"FIXED_AMOUNT",
}

// validDiscountTypeEnumValue provides a map of DiscountTypes for fast verification of use input
var validDiscountTypeEnumValues = map[DiscountType]struct{}{
	"PERCENTAGE": {},
	"FIXED_AMOUNT": {},
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiscountType) IsValid() bool {
	_, ok := validDiscountTypeEnumValues[v]
	return ok
}

// NewDiscountTypeFromValue returns a pointer to a valid DiscountType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiscountTypeFromValue(v string) (DiscountType, error) {
	ev := DiscountType(v)
	if ev.IsValid() {
		return ev, nil
	}

	return "", fmt.Errorf("invalid value '%v' for DiscountType: valid values are %v", v, AllowedDiscountTypeEnumValues)
}



// AssertDiscountTypeRequired checks if the required fields are not zero-ed
func AssertDiscountTypeRequired(obj DiscountType) error {
	return nil
}

// AssertDiscountTypeConstraints checks if the values respects the defined constraints
func AssertDiscountTypeConstraints(obj DiscountType) error {
	return nil
}
