// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen


import (
	"time"
)



type ProductResponse struct {

	// Уникальный идентификатор товара
	Id string `json:"id"`

	// Название товара
	Name string `json:"name"`

	// Описание товара
	Description string `json:"description,omitempty"`

	// Цена товара в рублях
	Price float64 `json:"price"`

	// Остаток на складе
	Stock int32 `json:"stock"`

	// Категория товара
	Category string `json:"category"`

	Status ProductStatus `json:"status"`

	// ID продавца, которому принадлежит товар
	SellerId string `json:"seller_id"`

	// Время создания товара
	CreatedAt time.Time `json:"created_at"`

	// Время последнего обновления товара
	UpdatedAt time.Time `json:"updated_at"`
}

// AssertProductResponseRequired checks if the required fields are not zero-ed
func AssertProductResponseRequired(obj ProductResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
		"price": obj.Price,
		"stock": obj.Stock,
		"category": obj.Category,
		"status": obj.Status,
		"seller_id": obj.SellerId,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertProductResponseConstraints checks if the values respects the defined constraints
func AssertProductResponseConstraints(obj ProductResponse) error {
	return nil
}
