// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen




type OrderItemResponse struct {

	// Уникальный идентификатор позиции
	Id string `json:"id"`

	// ID товара
	ProductId string `json:"product_id"`

	// Количество единиц товара
	Quantity int32 `json:"quantity"`

	// Цена за единицу на момент заказа (снапшот)
	PriceAtOrder float64 `json:"price_at_order"`
}

// AssertOrderItemResponseRequired checks if the required fields are not zero-ed
func AssertOrderItemResponseRequired(obj OrderItemResponse) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"product_id": obj.ProductId,
		"quantity": obj.Quantity,
		"price_at_order": obj.PriceAtOrder,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOrderItemResponseConstraints checks if the values respects the defined constraints
func AssertOrderItemResponseConstraints(obj OrderItemResponse) error {
	return nil
}
