// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Маркетплейс API
 *
 * API для маркетплейса с полной бизнес-логикой: - Управление товарами (CRUD) - Управление заказами с валидацией - Промокоды и скидки - Аутентификация и авторизация (JWT) - Ролевая модель доступа (USER, SELLER, ADMIN) 
 *
 * API version: 1.0.0
 */

package gen




type UserRegisterRequest struct {

	// Email пользователя
	Email string `json:"email"`

	// Пароль (минимум 8 символов)
	Password string `json:"password"`

	Role UserRole `json:"role"`
}

// AssertUserRegisterRequestRequired checks if the required fields are not zero-ed
func AssertUserRegisterRequestRequired(obj UserRegisterRequest) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"password": obj.Password,
		"role": obj.Role,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserRegisterRequestConstraints checks if the values respects the defined constraints
func AssertUserRegisterRequestConstraints(obj UserRegisterRequest) error {
	return nil
}
